base_url = "https://4l0n3r.github.io/"
title = "Johny"
description = "Aka 4l0n3r"
build_search_index = false
generate_feeds = true
compile_sass = true
minify_html = true
taxonomies = [{ name = "tags" }]

[markdown]
highlight_code = true
highlight_theme = "ayu-light"

[extra]
toc = true
use_cdn = false
favicon = "/icon/favicon.png"
theme = "toggle"              # light, dark, auto, toggle
fancy_code = true
dynamic_note = true           # a note that can be toggled
mathjax = true
mathjax_dollar_inline_enable = true
repo_url = "https://github.com/4l0n3r/4l0n3r.github.io"

menu = [
    { name = "/blogs", url = "/blogs", weight = 1 },
    { name = "/writeups", url = "/writeups", weight = 2 },
    { name = "/projects", url = "/projects", weight = 3 }
]

socials = [
    { name = "twitter", url = "https://x.com/0xJ0hny", icon = "twitter" },
    { name = "github", url = "https://github.com/4l0n3r/", icon = "github" },
    { name = "linkedin", url = "https://www.linkedin.com/in/johny-vasamsettti/", icon = "linkedin" },
    { name = "Email", url = "mailto: vasamsetti.johny@gmail.com", icon = "email" },
]

stylesheets = [
    # "custom.css"    # at /static/custom.css
]

[extra.analytics]
enabled = false

[extra.analytics.goatcounter]
user = "your_user"
host = "example.com" # default= goatcounter.com

[extra.analytics.umami]
website_id = "43929cd1-1e83...."
host_url = "https://stats.mywebsite.com" # default: https://api-gateway.umami.dev/
